# -*- coding: utf-8 -*-
"""minha_garagem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqKskXplixXlJkb5PQcKgwwO90TP1KsC
"""

from veiculo import Veiculo, Carro, Moto

# Crie pelo menos 3 veículos (seus dados, não os do exemplo!)
v1 = Carro('Volkswagen', 'Gol', 2019, 4)
v2 = Moto('Yamaha', 'Fazer 250', 2021, 250)
v3 = Carro('Fiat', 'Argo', 2020, 4)

garagem = [v1, v2, v3]

# Percorra a lista e imprima cada veículo
for v in garagem:
    print(v)

# Imprima quantos são Carros e quantos são Motos
carros = [v for v in garagem if isinstance(v, Carro)]
motos  = [v for v in garagem if isinstance(v, Moto)]
print(f'Carros: {len(carros)} | Motos: {len(motos)}’)